apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server-ipv4-local
  namespace: demo
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: server
  sessionAffinity: None
  type: LoadBalancer
  ports:
  - name: tcp
    port: 4444
    protocol: TCP
    targetPort: 4444
