$Global:SUBSCRIPTION_ID="b8c06bcd-5024-43fa-9507-691b5623f59a"
$Global:RG_NAME="pper-vfptest-rg"
$Global:LOCATION="westeurope"
$Global:CLUSTER_NAME="pper-vfptest-aks"
$Global:NODE_USER_NAME="prince"
$Global:NODE_PASSWORD="prince@123456123456"
$Global:K8S_VERSION="1.32.7"
$Global:NODE_POOL_NAME="npwin"
$Global:NODE_COUNT="2"


$Global:HPC_NAME="hpc-ds-win"
$Global:NAMESPACE  ="demo"
$Global:SERVER_POD_DEPLOYMENT="tcp-server"
$Global:LOGS_ROOT_DIR="C:\Users\ppereira\Logs\Bugs\Cilium\KubeProxyDualStackbehav"