apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-real-index
  namespace: demo
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      nodeSelector:
        kubernetes.azure.com/os-sku: Windows2022
      containers:
        - name: server
          image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
          ports:
            - containerPort: 80