apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpserver
  name: __SERVICENAME__
  namespace: __NAMESPACE__
spec:
  __TRAFFICPOLICY__
  ipFamilies:
  - __IPFAMILY__
  ipFamilyPolicy: SingleStack
  selector:
    app: httpserver
  sessionAffinity: None
  type: LoadBalancer
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 80
