apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpserver
  name: httpserver-ipv4-cluster
  namespace: demo
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: httpserver
  sessionAffinity: None
  type: LoadBalancer
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 80
