apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server-prefer-dual-local
  namespace: demo
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
  selector:
    app: server
  sessionAffinity: None
  type: LoadBalancer
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 80
