apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: demo
  labels:
    app: server
spec:
  replicas: 8
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: server
          image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
          ports:
            - containerPort: 80