apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: demo
  labels:
    app: client
spec:
  replicas: 4
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: client
          image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
