apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server
  namespace: demo
  labels:
    app: tcp-server
spec:
  replicas: 6
  selector:
    matchLabels:
      app: tcp-server
  template:
    metadata:
      labels:
        app: tcp-server
    spec:
      nodeSelector:
        # "kubernetes.io/os": windows
        # "kubernetes.azure.com/os-sku": WindowsAnnual
        "kubernetes.azure.com/os-sku": Windows2022
      containers:
        - name: tcp-server
          image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
          ports:
            - containerPort: 80