apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  namespace: demo
  labels:
    app: httpserver
spec:
  replicas: 8
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      nodeSelector:
        # "kubernetes.io/os": windows
        # "kubernetes.azure.com/os-sku": WindowsAnnual
        "kubernetes.azure.com/os-sku": Windows2022
      containers:
        - name: httpserver
          image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
          ports:
            - containerPort: 80