apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
  namespace: demo
  labels:
    app: test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
        - name: test2
          image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
          ports:
            - containerPort: 80