apiVersion: v1
kind: Service
metadata:
  labels:
    app: tcp-server
  name: tcp-server-ipv6-local
  namespace: demo
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  selector:
    app: tcp-server
  sessionAffinity: None
  type: LoadBalancer
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 80
