apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpserver
  name: httpserver-prefer-dual-cluster
  namespace: demo
spec:
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
  selector:
    app: httpserver
  sessionAffinity: None
  type: LoadBalancer
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 80
